### ISSUE TITLE
Rendered video is not playing on chrome browser

### ISSUE THREAD

**Issue by Muratcol** [daybrush/scenejs-render#12]
Command:
```
render -i index.html --name scene -o output.mp4
```

And after the rendering operation finished, I upload the mp4 file to Google Cloud Storage, but when I try to reach the video by the link, the video cannot be played in the browser.

However, when I download the video from cloud storage, there is no problem with the video.

I tried to encode the video via FFMPEG but the result is the same.

Command: 
```
ffmpeg -y -i "output.mp4" -c:v libx264 -preset slow -crf 22 -pix_fmt yuv420p -c:a libvo_aacenc -b:a 128k "output_encoded.mp4"
```

**Comment by daybrush** [comment]
@Muratcol 

It is most likely a problem with ffmpeg. Let's find out. It might take a little while.

**Comment by Muratcol** [comment]
It's been too long since I ask the question but I'll write solution of the issue here in case anyone has a similar problem. 

When uploading to Google Cloud Storage, it should be loaded with the `gzip: false` option. If it's set `true`, the videos do not play through the browser.
