### ISSUE TITLE
Freeze at the end of the rendered video

### ISSUE THREAD

**Issue by Muratcol** [daybrush/scenejs-render#14]
I convert the html content I created with Scene.js into videos with sound. I' very happy with the Scene.js performance, but there are freezes on the videos that are created. 

No matter how hard I looked for the reason, I couldn't find a reason for it.

[video](https://streamable.com/toli09)

I forked the project and was testing with this script:

```bash
node ./index.js -i examples/index.html --fps 24 --duration 12 --width 678 --height 508 --output output.webm
```
And this is the html file I'm using: [index.zip](https://github.com/daybrush/scenejs-render/files/8440918/index.zip)

**Comment by ironyee** [comment]
@Muratcol 
I can't access the zip file. Could you share the file again?

**Comment by Muratcol** [comment]
@ironyee  sorry, I updated the link.

Also, since I asked the question, I've been dealing with it and I want to make some updates about the problem.

In the rendering I made on my own computer, the video works without any problems.

However, my production product is running on cloud run and many freezes occur in rendering in cloud run. The main difference between the two systems is CPU process speed. 

The problem goes away when I add a waiting time(1 second) between screenshots. But the processing time slows down a lot.

**Comment by daybrush** [comment]
@Muratcol 

OK The problem was reproduced. I'll figure it out and fix it soon.

**Comment by daybrush** [comment]
@Muratcol 

`@scenejs/render` 0.11.0 is released.

its' seeking timing issue and solved problem.

Thank you :)

**Comment by Muratcol** [comment]
@daybrush 

Uhm... I'm started having this error:

```
spawn render EACCES
```

Do you know why?

**Comment by Muratcol** [comment]
@daybrush 

Error:
```
        "errno": -13,
        "code": "EACCES",
        "syscall": "spawn render",
        "path": "render",
        "spawnargs": [
            "-b",
            "8192k",
            "-i",
            "/tmp/d1d97e81-ff16-4306-bfea-efd1f54c46c5/index.html",
            "-o",
            "/tmp/d1d97e81-ff16-4306-bfea-efd1f54c46c5_rendered.mp4",
            "-d",
            6,
            "-w",
            1920,
            "-h",
            1080,
            "-f",
            25,
            "-M",
            2,
            "-F",
            "./bin/ffmpeg/ffmpeg"
```
Stack:
```
"Error: spawn render EACCES\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)\n    at onErrorNT (node:internal/child_process:477:16)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"
```

**Comment by daybrush** [comment]
@Muratcol 

I can't give you a detailed method, but it doesn't seem to be authorized.

1. Give permission to the folder where the render module is installed, or
2. Delete`render` module and install it again with sudo privileges.

**Comment by Muratcol** [comment]
Yay 🎊  It's work like a charm! Without delays, it's much faster! 

Thank you so much @daybrush
