### ISSUE TITLE
404 Broken link!

### ISSUE THREAD

**Issue by BaseMax** [daybrush/scenejs-render#26]
https://daybrush.com/scenejs-render/

> <p align="middle"><a href="https://daybrush.com/scenejs-render"><strong>Official Site</strong></a> &nbsp;/&nbsp; <a href="https://daybrush.com/scenejs-render/release/latest/doc"><strong>API</strong></a> &nbsp;/&nbsp; <a href="https://github.com/daybrush/scenejs"><strong>Scene.js</strong></a> &nbsp;/&nbsp; <a href="https://github.com/daybrush/scena"><strong>Main Project</strong></a></p>

https://raw.githubusercontent.com/daybrush/scenejs-render/master/README.md

**Comment by daybrush** [comment]
@BaseMax  

okay. I made the demo link work.

Thank you :)

**Comment by BaseMax** [comment]
You are welcome.
