### ISSUE TITLE
Calling render function in NodeJS produces puppeteer error

### ISSUE THREAD

**Issue by usmanpakistan** [daybrush/scenejs-render#27]
## Environments
* OS name: 
* Scene.js Component Version: 0.15
* Component Name: Render
* Component version: 0.15

## Description
Calling the @scenejs/render function in NodeJS produces a puppeteer error. The code was copied from the readme file

```
const render = require("@scenejs/render")

render.render({
  input: "./index.html",
  name: "scene",
  output: "output.mp4",
  ffmpegPath: "e://ffmpeg/ffmpeg/ffmpeg.exe",
  width:1080,
});
```
![756951547472fc6bb3a423a28f46c496](https://user-images.githubusercontent.com/9464992/230697304-50d46410-810e-43d5-943a-afba6a8f32b1.png)

**Comment by daybrush** [comment]
@usmanpakistan 

oh sorry I need to set a default value for scale, but I'm missing it.

Can you temporarily set the scale to 1?
```
   width:1080;
   scale: 1
```

**Comment by daybrush** [comment]
@usmanpakistan 

0.15.1 is released. Check it again.

**Comment by usmanpakistan** [comment]
@daybrush Also any error thrown by Puppeteer is not handled properly. Can you handle puppeteer exceptions in utils.ts file in openPage function

**Comment by daybrush** [comment]
@usmanpakistan 

what error is happening? I will add handling according to your error.

**Comment by usmanpakistan** [comment]
I am using the @scensjs/render function in a NodeJS program. In my case, the program receives the path of the HTML file as a param. 

1. It seems that passing a non-existent HTML file throws puppeteer error. 
2. Another case was when puppeteer was not able to access chrome and it threw an error. 
3. When scale param was not set, puppeteer would also throw an error. 
Similarly, puppeteer will throw a lot of errors based and it would be great it newPage, goto and setViewport function calls were put inside a try-catch block

**Comment by daybrush** [comment]
@usmanpakistan 

0.15.2 is released. Thank you :)
