### ISSUE TITLE
How to track progress with render.render

### ISSUE THREAD

**Issue by usmanpakistan** [daybrush/scenejs-render#30]
## Environments
* OS name: Ubuntu
* Scene.js Component Version: 0.15
* Component Name (Render, Recorder): renderer
* Component version: 0.15
* Testable Address(optional):

## Description
I am using the below code to generate mp4 from animation in my nodeJS application. 
` const result = await  render.render(options)`
 
The render method shows progress messages _(e.g. Capture Progress: 48.143% (324 / 673))_ to the console. Is there a callback function of some sort which can allow us to capture the progress and report/log it somewhere

**Comment by usmanpakistan** [comment]
@daybrush Any feedback on it

**Comment by daybrush** [comment]
@usmanpakistan 

in the next version
1. I will add turning off the log.
2. I will add an event binding if you call it through a method.

and
  There are 2 types of events.
1. captureStart, capture, captureEnd
https://daybrush.com/scenejs-render/release/latest/doc/Recorder.html#.OnCapture
2. processVideoStart, processingVideo, processVideoEnd
https://daybrush.com/scenejs-render/release/latest/doc/Recorder.html#.OnProcess

You can get the same information from the console through these events.

It takes 2 days to apply. wait a munite.

**Comment by daybrush** [comment]
@usmanpakistan 

0.16.0 is released.


`created`, `noLog`, `logger` options are added.

You can get information through events.


```ts
    /**
     * Whether to show Scene.js's Render logs
     * @default true
     */
    noLog?: boolean;
    /**
     * A hook function called when an instance is created
     */
    created?: (inst: Recorder) => void;
    /**
     * Messages output from Scene.js Render can be received from the outside through a function.
     */
    logger?: (...messages) => void;
```

```js
render({
    input: "./test/test.html",
    fps: 60,
    ffmpegPath: "./ffmpeg",
    cache: true,
    noLog: true,
    logger: (...messages) => {
        console.log(messages);
    },
    created: inst => {
        inst.on("capture", e => {
            console.log(e.ratio);
        });
    },
});
```
